### ISSUE TITLE
Error whilst generating json file.

### ISSUE THREAD

**Issue by dheerajbhadani** [RussellLuo/grpc-pytools#1]
Whilst following the helloworld example instructions, I came across below mentioned error:

dheerajbhadani@grpc-pytools:~/grpc/grpc-pytools/examples/helloworld$ python -m grpc_tools.protoc -I. --pytools-ast_out=. helloworld.proto
protoc-gen-pytools-ast: program not found or is not executable
--pytools-ast_out: protoc-gen-pytools-ast: Plugin failed with status code 1.

**Comment by RussellLuo** [comment]
Just run:

```bash
$ protoc-gen-pytools-ast
```

and see if the command can be found correctly?

Have you installed `grpc-pytools` correctly? Or maybe you have installed it in virtualenv but run the command in global environment?

**Comment by dheerajbhadani** [comment]
I had installed `grpc-pytools` and did not receive any error so I assume that is correctly installed. However, I
 re-installed it and here is the console result for your reference :

 dheerajbhadani@grpc-pytools:~/grpc/grpc-pytools/grpc_pytools$ pip install grpc-pytools
Collecting grpc-pytools
  Using cached grpc_pytools-0.1.2-py2.py3-none-any.whl
Collecting python-restart (from grpc-pytools)
  Using cached Python_RESTArt-0.1.5-py2.py3-none-any.whl
Collecting marshmallow (from grpc-pytools)
  Using cached marshmallow-2.13.6-py2.py3-none-any.whl
Collecting grpcio (from grpc-pytools)
  Using cached grpcio-1.6.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting Werkzeug>=0.9 (from python-restart->grpc-pytools)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting six==1.9.0 (from python-restart->grpc-pytools)
  Using cached six-1.9.0-py2.py3-none-any.whl
Collecting click==4.0 (from python-restart->grpc-pytools)
  Using cached click-4.0-py2.py3-none-any.whl
Collecting python-easyconfig==0.1.6 (from python-restart->grpc-pytools)
  Using cached Python_EasyConfig-0.1.6-py2.py3-none-any.whl
Collecting futures>=2.2.0 (from grpcio->grpc-pytools)
  Using cached futures-3.1.1-py2-none-any.whl
Collecting enum34>=1.0.4 (from grpcio->grpc-pytools)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting protobuf>=3.3.0 (from grpcio->grpc-pytools)
  Using cached protobuf-3.4.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting PyYAML>=3.10 (from python-easyconfig==0.1.6->python-restart->grpc-pytools)
Collecting setuptools (from protobuf>=3.3.0->grpcio->grpc-pytools)
  Using cached setuptools-36.5.0-py2.py3-none-any.whl
Installing collected packages: Werkzeug, six, click, PyYAML, python-easyconfig, python-restart, marshmallow, futures, enum34, setuptools, protobuf, grpcio, grpc-pytools
Successfully installed PyYAML-3.12 Werkzeug-0.12.2 click-4.0 enum34-1.1.6 futures-3.1.1 grpc-pytools-0.1.2 grpcio-1.6.0 marshmallow-2.13.6 protobuf-3.4.0 python-easyconfig-0.1.6 python-restart-0.1.5 setuptools-36.5.0 six-1.11.0

Afer re-installation, I tried **protoc-gen-pytools-ast** command as you mentioned but got an response mentioning **command not found**
dheerajbhadani@grpc-pytools:~/grpc/grpc-pytools/grpc_pytools$ protoc-gen-pytools-ast
-bash: protoc-gen-pytools-ast: command not found

Am I missing anything?

Please note that I am using debian OS.

**Comment by RussellLuo** [comment]
Try this to see where `protoc-gen-pytools-ast` is located:

```bash
$ which protoc-gen-pytools-ast
```

and also check your `$PATH` environment to see if the above path is included.

**Comment by dheerajbhadani** [comment]
Thanks for the quick response.

after doing 

`$ which protoc-gen-pytools-ast`

I got to know that it was not available. I ran the installation command with sudo and it got installed.

dheerajbhadani@grpc-pytools:~/grpc/grpc-pytools/examples/helloworld$ which protoc-gen-pytools-ast
/usr/local/bin/protoc-gen-pytools-ast

now this command is working fine. Thanks! However, 
`$ python -m grpc_tools.protoc -I. --pytools-ast_out=. helloworld.proto`
is still throwing error as mentioned below:

dheerajbhadani@grpc-pytools:~/grpc/grpc-pytools/examples/helloworld$ python -m grpc_tools.protoc -I. --pytools-ast_out=. helloworld.proto
Traceback (most recent call last):
  File "/usr/local/bin/protoc-gen-pytools-ast", line 7, in <module>
    from grpc_pytools.protoc_plugins.ast import main
  File "/home/dheerajbhadani/.local/lib/python2.7/site-packages/grpc_pytools/protoc_plugins/ast.py", line 6, in <module>
    from .generator import Generator
  File "/home/dheerajbhadani/.local/lib/python2.7/site-packages/grpc_pytools/protoc_plugins/generator.py", line 7, in <module>
    from google.protobuf.compiler import plugin_pb2 as plugin
ImportError: No module named compiler
--pytools-ast_out: protoc-gen-pytools-ast: Plugin failed with status code 1.

**Comment by RussellLuo** [comment]
Have you installed `grpcio-tools`, see [here](https://github.com/RussellLuo/grpc-pytools#prerequisites) for instructions if not.

**Comment by dheerajbhadani** [comment]
grpcio and grpcio-tools are already installed.

**Comment by RussellLuo** [comment]
Which version is your `protobuf`? My version is `3.3.0`:

```bash
$ python
>>> from google import protobuf
>>> protobuf.__version__
'3.3.0'
```

And I found an issue https://github.com/google/protobuf/issues/2895, seems like the same problem.

**Comment by dheerajbhadani** [comment]
You nailed it @RussellLuo !
I had protobuf 3.4.0 installed. However switching to protobuf 3.3.0 worked like charm.

Thanks a lot for all your help. Much appreciated!

Confirming that after installation of protobuf 3.3.0, everything worked as intended.

Many thanks,
Dheeraj
