### ISSUE TITLE
Something Missed In Import template 

### ISSUE THREAD

**Issue by popo4u** [RussellLuo/grpc-pytools#3]
There is a problem in Import Template.  Something is missed when use pip install  ( pythoninc.py line 48  '\n{import_pb2}_grpc'.format .... ) .
This problem would’t be happen when install from source code , i guess the library in pypi is out out date.
can you spend some time to solve this problem,  pip makes me lazy!  Thanks...

**Comment by RussellLuo** [comment]
Done, [grpc-pytools 0.1.3](https://pypi.org/project/grpc-pytools/) is released.

**Comment by popo4u** [comment]
I helps me a lot. 3Q.. ^_^
