### ISSUE TITLE
Installation fails due to conflicting six version

### ISSUE THREAD

**Issue by NeolithEra** [RussellLuo/grpc-pytools#4]
Hi, users are unable to run grpc-pytools due to dependency conflict with _**six**_ package.

As shown in the following full dependency graph of **_grpc-pytools_**, **_grpcio_** requires _**six>=1.5.2**_，while **_python-restart_** requires _**six==1.9.0**_.

According to pip’s _“first found wins”_ installation strategy, _**six==1.12.0**_ is the actually installed version. However, _**six==1.12.0**_ does not satisfy _**six==1.9.0**_.

### Dependency tree
```
grpc-pytools-0.1.3
| +-grpcio(version range:*)
| | +-six(version range:>=1.5.2)
| +-marshmallow(version range:*)
| +-python-restart(version range:*)
| | +-click(version range:==4.0)
| | +-python-easyconfig(version range:==0.1.6)
| | +-six(version range:==1.9.0)
| | +-werkzeug(version range:>=0.9)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution


1.	Reverse the declaration order of python-restart and grpcio into the requirement file, to allow six==1.9.0 to be installed. Then this conflict can be solved.

2.	Add a direct dependency six==1.9.0 into the requirement file.

Which solution do you prefer, 1 or 2?
@RussellLuo  Please let me know your choice. I can submit a PR to solve this issue.

**Comment by RussellLuo** [comment]
@NeolithEra Thanks for your suggestion!

According to your description, I think the **root cause** is in `python-restart`, so I have updated its version requirements.

Feel free to reopen this issue if the problem is not fixed :)
